### ISSUE TITLE
板块设计

### ISSUE THREAD

**Issue by lcy19** [OS-ABC/HelloWorld#9]
项目可以分出一个资源模块吗？比方说markdown 文件的使用说明？
如果需要 算法模块，自己也可以贡献力量。

**Comment by zhangqixun** [comment]
有这个规划的。Markdown文档格式说明可以单独一个文件，可以放在 https://github.com/OS-ABC/HelloWorld/tree/master/doc下面，单独建立一个目录。
算法有专门的算法区，在 https://github.com/OS-ABC/HelloWorld/tree/master/doc/Algorithms，在这里以后咱们可以放算法专区

**Comment by lcy19** [comment]
reduced
